### ISSUE TITLE
Only display Apple Pay payment method if supported

### ISSUE THREAD

**Issue by rvdsteege** [pronamic/wp-pronamic-pay-adyen#11]
With for example WooCommerce, our Apple Pay gateway is displayed as payment method at checkout even though this might not be supported by the browser/device.

A customer shared below CSS to only display this payment method in Safari,

```css
.payment_method_pronamic_pay_apple_pay {
	display: none
}

@media not all and (min-resolution:.001dpcm) {
	@supports (-webkit-appearance:none) and (display:flow-root) {
		/* Safari */
		.payment_method_pronamic_pay_apple_pay {
			display: block !important;
		}
	}
}
```

However, these CSS hacks seems to need updates on browser updates:
- https://stackoverflow.com/a/25975282/9993000
- https://browserstrangeness.bitbucket.io/css_hacks.html#safari

Another way to only display the Apple Pay payment method if applicable, would be by checking `window.ApplePaySession` as described in [Checking for Apple Pay Availability](https://developer.apple.com/documentation/apple_pay_on_the_web/apple_pay_js_api/checking_for_apple_pay_availability).

_Internal Help Scout ticket: https://secure.helpscout.net/conversation/1798706229/23596_
